// Reduce Arcane Essence generated by loot tables by exactly 20% on average.
// Multiples of five scale exactly (for example, 10 becomes 8). For smaller
// stacks, probabilistic rounding prevents integer rounding from over-nerfing.
LootJS.modifiers(event => {
  event.addTableModifier(/.*/)
    .modifyLoot('irons_spellbooks:arcane_essence', item => {
      const scaledCount = item.count * 0.8
      let reducedCount = Math.floor(scaledCount)

      if (Math.random() < scaledCount - reducedCount) {
        reducedCount++
      }

      if (reducedCount <= 0) return Item.empty

      item.setCount(reducedCount)
      return item
    })
})
