const IRONS_SPELLBOOKS_INKS = [
  'irons_spellbooks:common_ink',
  'irons_spellbooks:uncommon_ink',
  'irons_spellbooks:rare_ink',
  'irons_spellbooks:epic_ink',
  'irons_spellbooks:legendary_ink'
]

// Keep only half of all inks generated by loot tables. This preserves the
// mod's existing rarity weights while halving the expected amount of ink loot.
LootJS.modifiers(event => {
  event.addTableModifier(/.*/)
    .modifyLoot(IRONS_SPELLBOOKS_INKS, item => {
      if (Math.random() < 0.5) return Item.empty
      return item
    })
})
