#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true
