		[types.wood_type.domum_ornamentum]
			#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
			cactus = true
			cactus_extra = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.leaves_type.alexscaves]
			ancient = true
